import os
os.system("pip install discord")
os.system("pip install ping3")
os.system("pip install aiohttp")
os.system("pip install asyncio")
os.system("pip install random")
os.system("pip install requests")
os.system("pip install psutil")
os.system("pip install threading")
os.system("pip install bs4")
os.system("pip install speedtest-cli")
os.system("pip install PySocks")
os.system("pip install cfscrape")
os.system("pip install datetime")
os.system("pip install ssl")
os.system("pip install imcplib")
os.system("pip install scapy")
os.system("Npm install mongoose")
os.system("Npm install keyv")
os.system("Npm install dotenv")
os.system("Npm install @keyv/sqlite")
os.system("Npm install cpu-stat")
os.system("npm install chalk")
os.system("npm install fake-useragent")
os.system("npm install request")
os.system("npm install request")





os.system("Npm install moment-duration-format")
os.system("npm i cloudflare-bypasser")
os.system("npm i cloudscraper")
os.system("sudo apt-get install nodejs")
os.system("sudo apt-get install npm")
os.system("npm i events")
os.system("npm i fs")
os.system("npm i url")
os.system("npm i net")
os.system("npm i cloudscraper")
os.system("npm i request")
os.system("npm i randomstring")
os.system("npm i cluster")
os.system("npm i hcaptcha-solver")
os.system("ulimit -n 999999")
os.system("chmod +x *")
os.system("sudo python3 stanley.py")
os.system("npm install user-agents")
os.system("npm install header-generator")
os.system("npm install moment")
os.system("npm install https")
os.system("npm install path")
os.system("npm install puppeteer")
os.system("npm install axios")